# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, Test and Lint

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build/test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9"] # no 3.10 yet - see https://github.com/bbc/audio-offset-finder/issues/20

    steps:
    - uses: actions/checkout@v3
    
    - name: Install FFMPEG (Windows-only)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg
      
    - name: Install FFMPEG (Non-Windows)
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          brew install ffmpeg
        elif [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install -y ffmpeg
        fi
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pipreqs
        # create a requirements.txt by examining source code
        ln bin/audio-offset-finder bin/audio-offset-finder.py
        pipreqs
        rm bin/audio-offset-finder.py
        if [ -f requirements.txt ]; then echo "requirements.txt"; cat requirements.txt; pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 bin/audio-offset-finder . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest
